const USER_INFO = 'USER_INFO';
const CUSTOMER = 'CUSTOMER';
const CUSTOMER_BASIC_INFO = 'CUSTOMER_BASIC_INFO';
const CUSTOMER_CURRENT_PLAN = 'CUSTOMER_CURRENT_PLAN';
const PAGE_NO = 'PAGE_NO';
const PROFILE_PIC_URI = 'PROFILE_PIC_URI';
const PLAN_DETAILS = 'PLAN_DETAILS';
const ID_PROOF_URI = 'ID_PROOF_URI';
const ADDRESS_PROOF_URI = 'ADDRESS_PROOF_URI';
const SIGNATURE_PROOF_URI = 'SIGNATURE_PROOF_URI';
const CUSTOMER_KYC = 'CUSTOMER_KYC';
const IS_AUTHENTICATED = 'IS_AUTHENTICATED';

export default {
  USER_INFO,
  CUSTOMER,
  CUSTOMER_BASIC_INFO,
  CUSTOMER_CURRENT_PLAN,
  PAGE_NO,
  PROFILE_PIC_URI,
  PLAN_DETAILS,
  ID_PROOF_URI,
  ADDRESS_PROOF_URI,
  SIGNATURE_PROOF_URI,
  CUSTOMER_KYC,
  IS_AUTHENTICATED,
};
