export default {
  // serverUrl: 'https://dev.vbc.cloudtaru.com',
  // wssURL: 'wss://dev.vbc.cloudtaru.com',

  //   serverUrl: 'https://admin.bcndiginet.com',
  //   wssURL: 'wss://admin.bcndiginet.com',
  //   REACT_APP_CLIENT_NAME:"BCN DIGINET",
  //   REACT_APP_API_URL_HELPDESK : "https://admin.bcndiginet.com:7004",
  //   REACT_APP_API_URL_ADMIN :"https://admin.bcndiginet.com:7001",
  //   REACT_APP_API_URL_SERVICES : "https://admin.bcndiginet.com:7003",
  //   REACT_APP_API_URL_CUSTOMER : "https://admin.bcndiginet.com:7005",
  //   REACT_APP_API_URL_BILLING : "https://admin.bcndiginet.com:7006",
  //   REACT_APP_API_URL_NETWORK : "https://admin.bcndiginet.com:7012",
  //   REACT_APP_API_URL_STAFF : "https://admin.bcndiginet.com:7010",
  //   REACT_APP_API_URL_CAMPAIGN : "https://admin.bcndiginet.com:7008",
  //   Logo_Name: require('../assets/images/bcn_logo.png')

  //   REACT_APP_CLIENT_NAME: 'SKYLINE BROADBAND',
  //   serverUrl: 'https://admin.skylinebroadband.sparkradius.in',
  //   wssURL: 'wss://admin.skylinebroadband.sparkradius.in',
  //   REACT_APP_API_URL_HELPDESK: 'https://admin.skylinebroadband.sparkradius.in:7004',
  //   REACT_APP_API_URL_ADMIN: 'https://admin.skylinebroadband.sparkradius.in:7001',
  //   REACT_APP_API_URL_SERVICES: 'https://admin.skylinebroadband.sparkradius.in:7003',
  //   REACT_APP_API_URL_CUSTOMER: 'https://admin.skylinebroadband.sparkradius.in:7005',
  //   REACT_APP_API_URL_BILLING: 'https://admin.skylinebroadband.sparkradius.in:7006',
  //   REACT_APP_API_URL_NETWORK: 'https://admin.skylinebroadband.sparkradius.in:7007',
  //   REACT_APP_API_URL_STAFF: 'https://admin.skylinebroadband.sparkradius.in:7010',
  //   REACT_APP_API_URL_CAMPAIGN: 'https://admin.skylinebroadband.sparkradius.in:7008',
  //   Logo_Name: require('../assets/images/skyline_logo.png')

  REACT_APP_CLIENT_NAME: 'VBC ON FIBER',
  serverUrl: 'https://admin.vbctv.in',
  wssURL: 'wss://admin.vbctv.in',
  REACT_APP_API_URL_HELPDESK: 'https://admin.vbctv.in:7004',
  REACT_APP_API_URL_ADMIN: 'https://admin.vbctv.in:7001',
  REACT_APP_API_URL_SERVICES: 'https://admin.vbctv.in:7003',
  REACT_APP_API_URL_CUSTOMER: 'https://admin.vbctv.in:7005',
  REACT_APP_API_URL_BILLING: 'https://admin.vbctv.in:7006',
  REACT_APP_API_URL_NETWORK: 'https://admin.vbctv.in:7007',
  REACT_APP_API_URL_STAFF: 'https://admin.vbctv.in:7010',
  REACT_APP_API_URL_CAMPAIGN: 'https://admin.vbctv.in:7008',
  Logo_Name: require('../assets/images/vbc_logo.png'),

  // REACT_APP_CLIENT_NAME: 'VBC ON FIBER',
  // serverUrl: 'https://qa.sparkradius.in',
  // wssURL: 'wss://qa.sparkradius.in',
  // REACT_APP_API_URL_HELPDESK: 'https://qa.sparkradius.in:7004',
  // REACT_APP_API_URL_ADMIN: 'https://qa.sparkradius.in:7001',
  // REACT_APP_API_URL_SERVICES: 'https://qa.sparkradius.in:7003',
  // REACT_APP_API_URL_CUSTOMER: 'https://qa.sparkradius.in:7005',
  // REACT_APP_API_URL_BILLING: 'https://qa.sparkradius.in:7006',
  // REACT_APP_API_URL_NETWORK: 'https://qa.sparkradius.in:7007',
  // REACT_APP_API_URL_STAFF: 'https://qa.sparkradius.in:7010',
  // REACT_APP_API_URL_CAMPAIGN: 'https://qa.sparkradius.in:7008',
  // Logo_Name: require('../assets/images/vbc_logo.png'),

  // REACT_APP_CLIENT_NAME: 'VBC ON FIBER',
  // serverUrl: ' https://dev.vbc.cloudtaru.com:',
  // wssURL: 'wss://dev.vbc.cloudtaru.com',
  // REACT_APP_API_URL_HELPDESK: 'https://dev.vbc.cloudtaru.com:7004',
  // REACT_APP_API_URL_ADMIN: 'https://dev.vbc.cloudtaru.com:7001',
  // REACT_APP_API_URL_SERVICES: 'https://dev.vbc.cloudtaru.com:7003',
  // REACT_APP_API_URL_CUSTOMER: 'https://dev.vbc.cloudtaru.com:7005',
  // REACT_APP_API_URL_BILLING: 'https://dev.vbc.cloudtaru.com:7006',
  // REACT_APP_API_URL_NETWORK: 'https://dev.vbc.cloudtaru.com:7007',
  // REACT_APP_API_URL_STAFF: 'https://dev.vbc.cloudtaru.com:7010',
  // REACT_APP_API_URL_CAMPAIGN: ' https://dev.vbc.cloudtaru.com:7008',
  // Logo_Name: require('../assets/images/vbc_logo.png'),

  // serverUrl: 'https://admin.vbctv.in',
  // wssURL: 'wss://admin.vbctv.in',

  //MMI
};
