export default {
  colon: ':',

  // REACT_APP_CLIENT_NAME: 'VBC ON FIBER',
  // Notication_Display_Name: 'VBC Employee App',
  // REACT_APP_API_URL: 'https://qa.sparkradius.in',
  // REACT_APP_API_URL_FRANCHISE: 'https://qa.sparkradius.in:7001',
  // REACT_APP_API_URL_HELPDESK: 'https://qa.sparkradius.in:7004',
  // REACT_APP_API_URL_ADMIN: 'https://qa.sparkradius.in:7001',
  // REACT_APP_API_URL_SERVICES: 'https://qa.sparkradius.in:7003',
  // REACT_APP_API_URL_CUSTOMER: 'https://qa.sparkradius.in:7005',
  // REACT_APP_API_URL_BILLING: 'https://qa.sparkradius.in:7006',
  // REACT_APP_API_URL_NETWORK: 'https://qa.sparkradius.in:7007',
  // REACT_APP_API_URL_STAFF: 'https://qa.sparkradius.in:7010',
  // REACT_APP_API_URL_CAMPAIGN: 'https://qa.sparkradius.in:7008',
  // Logo_Image: require('../../../assets/images/vbc_logo.png'),
  // serverUrl: 'https://qa.sparkradius.in',
  // wssURL: 'wss://qa.sparkradius.in',

  REACT_APP_CLIENT_NAME: 'VBC ON FIBER',
  Notication_Display_Name: 'VBC Employee App',
  REACT_APP_API_URL: 'https://admin.vbctv.in',
  REACT_APP_API_URL_FRANCHISE: 'https://admin.vbctv.in:7001',
  REACT_APP_API_URL_HELPDESK: 'https://admin.vbctv.in:7004',
  REACT_APP_API_URL_ADMIN: 'https://admin.vbctv.in:7001',
  REACT_APP_API_URL_SERVICES: 'https://admin.vbctv.in:7003',
  REACT_APP_API_URL_CUSTOMER: 'https://admin.vbctv.in:7005',
  REACT_APP_API_URL_BILLING: 'https://admin.vbctv.in:7006',
  REACT_APP_API_URL_NETWORK: 'https://admin.vbctv.in:7007',
  REACT_APP_API_URL_STAFF: 'https://admin.vbctv.in:7010',
  REACT_APP_API_URL_CAMPAIGN: 'https://admin.vbctv.in:7008',
  Logo_Image: require('../../../assets/images/vbc_logo.png'),
  serverUrl: 'https://admin.vbctv.in',
  wssURL: 'wss://admin.vbctv.in',

  // REACT_APP_CLIENT_NAME : "VBC ON FIBER",
  // Notication_Display_Name : "VBC Employee App",
  // REACT_APP_API_URL : 'https://dev.vbc.cloudtaru.com',
  // REACT_APP_API_URL_FRANCHISE : 'https://dev.vbc.cloudtaru.com:7001',
  // REACT_APP_API_URL_HELPDESK : 'https://dev.vbc.cloudtaru.com:7004',
  // REACT_APP_API_URL_ADMIN : 'https://dev.vbc.cloudtaru.com:7001',
  // REACT_APP_API_URL_SERVICES  : 'https://dev.vbc.cloudtaru.com:7003',
  // REACT_APP_API_URL_CUSTOMER  : 'https://dev.vbc.cloudtaru.com:7005',
  // REACT_APP_API_URL_BILLING  : 'https://dev.vbc.cloudtaru.com:7006',
  // REACT_APP_API_URL_NETWORK  : 'https://dev.vbc.cloudtaru.com:7007',
  // REACT_APP_API_URL_STAFF  : 'https://dev.vbc.cloudtaru.com:7010',
  // REACT_APP_API_URL_CAMPAIGN  : 'https://dev.vbc.cloudtaru.com:7008',
  // Logo_Image: require('../../../assets/images/vbc_logo.png'),
  //   serverUrl: 'https://dev.vbc.cloudtaru.com',
  //   wssURL: 'wss://dev.vbc.cloudtaru.com',

  // serverUrl: 'https://admin.bcndiginet.com',
  // wssURL: 'wss://admin.bcndiginet.com',

  //MMI
  CLIENT_ID:
    '33OkryzDZsL-pz7DbYV4UU5IL-eNqPxypZfE4pVzxqc1wx-OW4W_tePLUcYmngRVqPvAiYqsNREEQDUsMkC6eA==',
  CLIENT_SECRET:
    'lrFxI-iSEg8T101oVBL6uHUHpajOR6cNJYJW1JoUVqZC9xxI8U1Ep7H8uVmmqjpMpVGq74iM-5-H7VC-H2qVARqYrw3dksOb',
  SDK_KEY: 'f7f45dfbed02afe98e83d034955a78d3',
};
